### ISSUE TITLE
Multiple channel Tasmota switch

### ISSUE THREAD

**Issue by jmbinette** [sgupta999/mqtt-bridge-smartthings#10]
Any plans on releasing support for a 6-channel switch device ?

I flashed my Geeni Power strip : 
https://blakadder.github.io/templates/geeni_GN-SW003.html

Would like to be able ton control power1, power2, etc. from MQTT

Thanks

**Comment by sgupta999** [comment]
It’s already supported. The way to do this would be -

You create 6 ST virtual switches one each for each channel.

As long as you have a tasmota template or your own custom template in tasmota for the 6 ch device :

Then tasmota publishes / subscribes to 
For channel 1 
Stat/blah blah/power1 on/off
Cmd/blah blah/power1 on/off

And for channel 2

Stat/blah blah/power2 on/off
Cmd/blah blah/power2 on/off


So for each of the virtual switches in ST u will create a device entry in devices.yml and subscribe to the appropriate topics on the right channel number - no different than a 2 channel device - just have to repeat the process 6 times instead of 2

**Comment by rhamblen** [comment]
echo what sandeep said...
I have 2, 3 and 4 channel devices working fine.
you have to just set up the devices.yml with each channel being an individual device.
you need to check how MQTT sends the message but typically with tasmota it is **POWER<n>** where <n> is a number relating to the channel you are switching.
In smartthings, you then use the virtual switch for each channel.
NOTE the name of the smartthings switch must be the same name as the device in the YML file.

**Comment by jmbinette** [comment]
Ok than you guys

I am curious however, what is the use of the custom device handlers in groovy code if we can setup devices in the yml config file and default virtual switches ?

**Comment by sgupta999** [comment]
The custom device handlers are pulling in tasmota specific code - like custom LWT to check device health (online/offline) and then I pull a bunch of other tasmota specific information - look at the image below 
![8822FBD1-CD17-46F6-BCB5-A9B372BA0FB2](https://user-images.githubusercontent.com/35128032/69636252-c98f6200-101b-11ea-9348-7461303ab3bf.png)

**Comment by sgupta999** [comment]
But if u r just interested in basic capabilities then that should do. If you want the view as the image instead of ST virtual switch use the tasmota switch or the combo tasmotasensorswitch provided.

So the DTH provided should cover the most basic scenarios of switches and contact sensors populated with tasmota specific info

**Comment by jmbinette** [comment]
Thanks !
I just edited the devices.yml config file but i don't see subscription in the log file. Do I also need to register the device in the MQTT bridge smartapp ?

**Comment by sgupta999** [comment]
yes in the smartapp you need to select and register devices you want to be controlled through the bridge. open the smartapp and go through the config menu -  remember to configure the bridge correctly and then register the bridge and devices with the smartapp

**Comment by jmbinette** [comment]
Just saw the line : 
deviceconfig: true


Ok another question, I created a device handler with 6 attributes : 
```
(1..6).each { n ->
                attribute "switch$n", "enum", ["on", "off"]
                command "on$n"
                command "off$n"
            }
```


In the devices.yml : 

 ```
subscribe:
    switch1:
        blablabla/stat/power1:
          command:
            'OFF': 'off1'
            'ON': 'on1'
  publish:
    switch1:
        blablabla/cmnd/power1:
  retain: 'false'
```

I don't seem to get subscribed ...

Any way to have it work or I need to create 1 device = 1 outlet ?
I have 3 power strips with 6 outlet each ... that makes a lot of devices ....

Thanks again.

Edit, I get in the log file : 

> 2019-11-26 22:33:33 PM info: ============================ALL POSSIBLE SUBSCRIPTIONS FROM ALL EXTERNAL DEVICES ===========================================
> 2019-11-26 22:33:33 PM info: Subscription *******/Network_Power_1/stat/power1   [Network_Power_1],[switch1],[{"OFF":"off1","ON":"on1"}]
> 2019-11-26 22:33:33 PM info: ============================================================================================================================

**Comment by sgupta999** [comment]
Lets see its not clear 
1. Did you create a custom device handler with 6 switch attributes and six different on / off implementations OR
2. did you create 6 separate devices

I think you did the the 1st one - it might be better for you two do the 2nd one. I will first describe the 2nd approach which should be straight forward and then describe for custom DTH which is more complex.

So for 6 individual outlets your device,yml should look like this

I am not seeing a device name in your devices.yml

**Comment by sgupta999** [comment]
Straightforward approach
=====================

devices.yml
```
---

Outlet1:
  subscribe:
    switch:     
        smartthings/stat/sonoff1/POWER1:
          command:
            'OFF': 'off'
            'ON': 'on'
  publish:
    switch:
        smartthings/cmnd/sonoff1/POWER1:
  retain: 'false' 

Outlet2:
  subscribe:
    switch:     
        smartthings/stat/sonoff1/POWER2:
          command:
            'OFF': 'off'
            'ON': 'on'
  publish:
    switch:
        smartthings/cmnd/sonoff1/POWER2:
  retain: 'false' 

Outlet3:
  subscribe:
    switch:     
        smartthings/stat/sonoff1/POWER3:
          command:
            'OFF': 'off'
            'ON': 'on'
  publish:
    switch:
        smartthings/cmnd/sonoff1/POWER3:
  retain: 'false' 

Outlet4:
  subscribe:
    switch:     
        smartthings/stat/sonoff1/POWER4:
          command:
            'OFF': 'off'
            'ON': 'on'
  publish:
    switch:
        smartthings/cmnd/sonoff1/POWER4:
  retain: 'false' 

Outlet5:
  subscribe:
    switch:     
        smartthings/stat/sonoff1/POWER5:
          command:
            'OFF': 'off'
            'ON': 'on'
  publish:
    switch:
        smartthings/cmnd/sonoff1/POWER5:
  retain: 'false' 

Outlet6:
  subscribe:
    switch:     
        smartthings/stat/sonoff1/POWER6:
          command:
            'OFF': 'off'
            'ON': 'on'
  publish:
    switch:
        smartthings/cmnd/sonoff1/POWER6:
  retain: 'false'   
```

make sure you go to smartapp on your phone select the switches and bridge in config.
that should do it - if the bridge is configured properly and connecting with server
